apiVersion: v1
kind: Pod
metadata:
  name: caddy-web-server
spec:
  containers:
    - name: caddy
      image: my-custom-caddy:latest
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
      startupProbe:
        httpGet:
          path: /
          port: 8080
        failureThreshold: 30
        periodSeconds: 10
